services:
  nginx:
    image: nginx:latest
    container_name: "nginx_${NAME}"
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - local_network
    ports:
      - "${PORT}:80"

  backend:
    container_name: "backend_${NAME}"
    stop_signal: SIGINT
    restart: always
    build:
      context: .
    working_dir: "/usr/src/app/bot"
    volumes:
      - .:/usr/src/app/bot
      - /var/run/docker.sock:/var/run/docker.sock
    command: [ "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080" ]
    env_file:
      - ".env"
    networks:
      - local_network
    expose:
      - 8080

networks:
  local_network:
    driver: bridge
